/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/component/login-screen.component';
import * as import2 from '../../../../src/component/app.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/service/user.service';
const styles_LoginScreenComponent:any[] = ([] as any[]);
export const RenderType_LoginScreenComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_LoginScreenComponent,
  data: {}
}
);
export function View_LoginScreenComponent_0(l:any):import0.ɵViewDefinition {
      return import0.ɵvid(0,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'page'
      ]
  ],(null as any),(null as any),(null as any),(null as any),(null as any)))],(null as any),(null as any));
}
function View_LoginScreenComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'login-screen',([] as any[]),(null as any),(null as any),(null as any),View_LoginScreenComponent_0,RenderType_LoginScreenComponent)),
    import0.ɵdid(57344,(null as any),0,import1.LoginScreenComponent,[
      import2.AppComponent,
      import3.Router,
      import4.UserService
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const LoginScreenComponentNgFactory:import0.ComponentFactory<import1.LoginScreenComponent> = import0.ɵccf('login-screen',import1.LoginScreenComponent,View_LoginScreenComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvY29tcG9uZW50L2xvZ2luLXNjcmVlbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvY29tcG9uZW50L2xvZ2luLXNjcmVlbi5jb21wb25lbnQudHMiLCJuZzovLy9FOi9saWIvR2l0L2ltcHJvdnBsdXMvYXBwL3NyYy9jb21wb25lbnQvbG9naW4tc2NyZWVuLmNvbXBvbmVudC50cy5Mb2dpblNjcmVlbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvY29tcG9uZW50L2xvZ2luLXNjcmVlbi5jb21wb25lbnQudHMuTG9naW5TY3JlZW5Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwicGFnZVwiPjwvZGl2PiIsIjxsb2dpbi1zY3JlZW4+PC9sb2dpbi1zY3JlZW4+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZCQ0FBO1FBQUE7UUFBQTtNQUFBO0VBQUE7Ozs7SUNBQTtnQkFBQTs7OztJQUFBO0tBQUE7OztJQUFBOzs7In0=
