/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/module/shared.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '@angular/router';
import * as import5 from '../../../../src/service/app.service';
import * as import6 from '../../../../src/service/user.service';
import * as import7 from '../../../../src/service/cart.service';
import * as import8 from '../../../../src/data/app-http';
class SharedModuleInjector extends import0.ɵNgModuleInjector<import1.SharedModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _RouterModule_3:import4.RouterModule;
  _SharedModule_4:import1.SharedModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __ɵi_6:import3.ɵi;
  __AppService_7:import5.AppService;
  __UserService_8:import6.UserService;
  __CartService_9:import7.CartService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  get _AppService_7():import5.AppService {
    if ((this.__AppService_7 == null)) { (this.__AppService_7 = new import5.AppService(this.parent.get(import8.AppHttp))); }
    return this.__AppService_7;
  }
  get _UserService_8():import6.UserService {
    if ((this.__UserService_8 == null)) { (this.__UserService_8 = new import6.UserService(this.parent.get(import8.AppHttp))); }
    return this.__UserService_8;
  }
  get _CartService_9():import7.CartService {
    if ((this.__CartService_9 == null)) { (this.__CartService_9 = new import7.CartService(this.parent.get(import8.AppHttp),this._UserService_8)); }
    return this.__CartService_9;
  }
  createInternal():import1.SharedModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._RouterModule_3 = new import4.RouterModule(this.parent.get(import4.ɵa,(null as any)),this.parent.get(import4.Router,(null as any)));
    this._SharedModule_4 = new import1.SharedModule();
    return this._SharedModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.RouterModule)) { return this._RouterModule_3; }
    if ((token === import1.SharedModule)) { return this._SharedModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    if ((token === import5.AppService)) { return this._AppService_7; }
    if ((token === import6.UserService)) { return this._UserService_8; }
    if ((token === import7.CartService)) { return this._CartService_9; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SharedModuleNgFactory:import0.NgModuleFactory<import1.SharedModule> = new import0.NgModuleFactory<any>(SharedModuleInjector,import1.SharedModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvbW9kdWxlL3NoYXJlZC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvbW9kdWxlL3NoYXJlZC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
