/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../src/view/iplus.view';
const styles_IPlusView:any[] = ([] as any[]);
export const RenderType_IPlusView:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_IPlusView,
  data: {}
}
);
function View_IPlusView_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'text'
      ]
      ],[[
        2,
        'noplus',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = (co.text == 'mprovplus');
    ck(v,0,0,currVal_0);
    const currVal_1:any = co.text;
    ck(v,1,0,currVal_1);
  });
}
export function View_IPlusView_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),16,'i',[[
        'class',
        'iplus'
      ]
      ],[[
        2,
        'white',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'bracket'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['['])),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'i'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['i'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'plus'
      ]
      ],[[
        2,
        'hideonopen',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['+'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_IPlusView_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'bracket'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[']'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import2.IPlusView = v.component;
    const currVal_2:any = co.text;
    ck(v,12,0,currVal_2);
  },(ck,v) => {
    var co:import2.IPlusView = v.component;
    const currVal_0:any = co.white;
    ck(v,0,0,currVal_0);
    const currVal_1:any = co.text;
    ck(v,8,0,currVal_1);
  });
}
function View_IPlusView_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'iplus',([] as any[]),(null as any),(null as any),(null as any),View_IPlusView_0,RenderType_IPlusView)),
    import0.ɵdid(122880,(null as any),0,import2.IPlusView,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const IPlusViewNgFactory:import0.ComponentFactory<import2.IPlusView> = import0.ɵccf('iplus',import2.IPlusView,View_IPlusView_Host_0,{
  white: 'white',
  text: 'text'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvdmlldy9pcGx1cy52aWV3Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L2xpYi9HaXQvaW1wcm92cGx1cy9hcHAvc3JjL3ZpZXcvaXBsdXMudmlldy50cyIsIm5nOi8vL0U6L2xpYi9HaXQvaW1wcm92cGx1cy9hcHAvc3JjL3RlbXBsYXRlL3ZpZXcvaXBsdXMudmlldy5odG1sIiwibmc6Ly8vRTovbGliL0dpdC9pbXByb3ZwbHVzL2FwcC9zcmMvdmlldy9pcGx1cy52aWV3LnRzLklQbHVzVmlld19Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxpIGNsYXNzPVwiaXBsdXNcIiBbY2xhc3Mud2hpdGVdPVwid2hpdGVcIj5cclxuICAgIDxzcGFuIGNsYXNzPVwiYnJhY2tldFwiPls8L3NwYW4+XHJcbiAgICA8c3BhbiBjbGFzcz1cImlcIj5pPC9zcGFuPlxyXG4gICAgPHNwYW4gY2xhc3M9XCJwbHVzXCIgW2NsYXNzLmhpZGVvbm9wZW5dPVwidGV4dFwiPis8L3NwYW4+XHJcbiAgICA8c3BhbiBjbGFzcz1cInRleHRcIiBbY2xhc3Mubm9wbHVzXT1cInRleHQgPT0gJ21wcm92cGx1cydcIiAqbmdJZj1cInRleHRcIj57e3RleHR9fTwvc3Bhbj5cclxuICAgIDxzcGFuIGNsYXNzPVwiYnJhY2tldFwiPl08L3NwYW4+XHJcbjwvaT4iLCI8aXBsdXM+PC9pcGx1cz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0lJO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXFFO01BQUE7TUFBQTtJQUFBO0lBQUE7Ozs7SUFBbEQ7SUFBbkIsU0FBbUIsU0FBbkI7SUFBcUU7SUFBQTs7Ozs7TUFKekU7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBdUM7TUFDbkM7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFzQjtJQUFRO01BQzlCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBZ0I7SUFBUTtNQUN4QjtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE2QztJQUFRO0lBQ3JEO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBb0Y7TUFDcEY7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFzQjtJQUFROzs7O0lBRDBCO0lBQXhELFVBQXdELFNBQXhEOzs7SUFKYTtJQUFqQixTQUFpQixTQUFqQjtJQUd1QjtJQUFuQixTQUFtQixTQUFuQjs7Ozs7SUNISjtnQkFBQTs7O0lBQUE7Ozs7Ozs7In0=
